# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
import numpy as np
array = np.random.randint(-1000, 1001, size=(10, 10))

min_value = np.min(array)
max_value = np.max(array)

print("Массив 10x10:")
print(array)
print("\nМинимальное значение:" + str(min_value))
print("Максимальное значение:" + str(max_value))

Массив 10x10:
[[-373 -575  788  496  950 -369 -719 -842 -594  -47]
 [-443  199   20  399  225  740 -972 -391  416 -212]
 [ 989 -393   59  203 -491 -168  111 -896 -166 -917]
 [  58 -356 -860  -26  124  614  868 -172  236 -944]
 [-386  109  665  836  180 -395  184  394  -56 -538]
 [ 621  846 -369  913 -915 -859  713  990 -257 -745]
 [ 830 -727    7  254 -491  278  864  845 -716   60]
 [ 203 -145 -340 -296 -387   64   38 -292  -56 -476]
 [-121 -717 -114 -594  801 -168 -283  440  399 -988]
 [-771  123 -435 -541 -664 -777 -775  455 -994  349]]

Минимальное значение:-994
Максимальное значение:990


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
import numpy as np
chessboard = np.zeros((8, 8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 != 0:
            chessboard[i,j]=1
print("Шахматная доска 8x8:")
for row in chessboard:
    print(row)

Шахматная доска 8x8:
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]
[0 1 0 1 0 1 0 1]
[1 0 1 0 1 0 1 0]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
z = np.arange(11)
for i in range(len(z)):
  if 3< z[i]< 8:
    z[i]*=-1
print(z)
import numpy as np
z = np.arange(11)
z[(z > 3) & (z < 8)] *= -1
print(z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [5]:
import numpy as np
z = np.random.rand(5, 10)
z_centered = z - z.mean(axis=1, keepdims=True)

print("Исходная матрица:")
print(z)
print("\nИтоговая матрица:")
print(z_centered)

Исходная матрица:
[[0.77025035 0.44999993 0.4008107  0.93315541 0.75194956 0.02520635
  0.0078903  0.65009486 0.64976678 0.26948694]
 [0.72068139 0.66508377 0.39139795 0.2687179  0.03614594 0.09360839
  0.1202585  0.88183273 0.65695707 0.24432588]
 [0.52257008 0.82516771 0.77200325 0.0144515  0.65951132 0.52463078
  0.55069081 0.91185973 0.6150905  0.32667094]
 [0.60585876 0.08349701 0.22205075 0.59510001 0.25416861 0.36259527
  0.85675565 0.56906855 0.32384143 0.56166689]
 [0.95463994 0.82364268 0.71382506 0.60776428 0.28416831 0.12512442
  0.17710566 0.99985004 0.4546282  0.30093514]]

Итоговая матрица:
[[ 0.27938923 -0.04086119 -0.09005042  0.44229429  0.26108844 -0.46565477
  -0.48297082  0.15923374  0.15890567 -0.22137417]
 [ 0.31278043  0.25718282 -0.016503   -0.13918306 -0.37175501 -0.31429256
  -0.28764245  0.47393178  0.24905612 -0.16357507]
 [-0.04969459  0.25290305  0.19973858 -0.55781316  0.08724666 -0.04763388
  -0.02157385  0.33959507  0.04282584 -0.24559372]
 [ 0.1623984

5. Поменяйте 1 и 2 строки матрицы

In [6]:
import numpy as np
z = np.arange(25).reshape(5,5)
z_swapped = z.copy()
z_swapped[0] = z[1]
z_swapped[1] = z[0]
print("Исходная матрица:")
print(z)
print("Матрица с переставленными строками:")
print(z_swapped)

Исходная матрица:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Матрица с переставленными строками:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [7]:
import numpy as np
z = np.random.random((10, 2))
x = z[:, 0]
y = z[:, 1]
r = np.sqrt(x**2 + y**2)
phi = np.arctan2(y, x)
polar_coords = np.column_stack((r, phi))
print("Декартовы координаты:")
print(z)
print("\nПолярные координаты (радиус, угол в радианах):")
print(polar_coords)

Декартовы координаты:
[[0.10464682 0.49905208]
 [0.90694244 0.27004932]
 [0.67359854 0.15129608]
 [0.12743229 0.59428668]
 [0.31253867 0.35661922]
 [0.31898185 0.05737621]
 [0.43537793 0.80711865]
 [0.89073019 0.68334803]
 [0.30278241 0.21590103]
 [0.02889916 0.08371203]]

Полярные координаты (радиус, угол в радианах):
[[0.50990581 1.36409993]
 [0.94629341 0.28939859]
 [0.69038069 0.22094195]
 [0.60779573 1.35956601]
 [0.47419161 0.85117779]
 [0.32410099 0.17796989]
 [0.91705749 1.07611032]
 [1.1226597  0.65440428]
 [0.37187423 0.61943521]
 [0.08855995 1.23838521]]


7. Заменить максимальный элемент массива на ноль

In [8]:
import numpy as np

z = np.random.random(10)
print("Исходный массив:")
print(z)
max_index = np.argmax(z)
z[max_index] = 0

print("Массив после замены максимального элемента на 0:")
print(z)

Исходный массив:
[0.39813128 0.92096185 0.69580243 0.09580588 0.30290065 0.14142707
 0.14392248 0.56702028 0.71970688 0.33808718]
Массив после замены максимального элемента на 0:
[0.39813128 0.         0.69580243 0.09580588 0.30290065 0.14142707
 0.14392248 0.56702028 0.71970688 0.33808718]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [9]:
import numpy as np
z = np.ones(10)
print("Первый массив:", z)
i = np.random.randint(0, len(z), 20)
unique_indices = np.unique(i)
z[unique_indices] += 1
print("Массив индексов i:", i)
print("Массив без повторений:", unique_indices)
print("Результат:")
print(z)

Первый массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Массив индексов i: [0 4 7 9 3 4 3 0 5 4 3 4 3 7 8 4 4 2 3 0]
Массив без повторений: [0 2 3 4 5 7 8 9]
Результат:
[2. 1. 2. 2. 2. 2. 1. 2. 2. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [10]:
import numpy as np
z = np.array([1, 2, 3, 4, 5])
new_length = len(z) + (len(z) - 1) * 3
result = np.zeros(new_length, dtype=z.dtype)
result[::4] = z
print(result)

[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


10. Найти ближайшее к заданному значению число в заданном массиве

In [11]:
import numpy as np
z = np.arange(100)  # Массив чисел от 0 до 99
v = np.random.uniform(0, 100)  # Случайное число от 0 до 100
idx = (np.abs(z - v)).argmin()
nearest_value = z[idx]
print(f"Случайное число v: {v}")
print(f"Ближайшее число в массиве z: {nearest_value}")

Случайное число v: 64.77166156197902
Ближайшее число в массиве z: 65


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?